config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "affirmations#random"

  resources :affirmations
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/affirmation.rb
class Affirmation < ApplicationRecord
  validates :text, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/affirmations_controller.rb
class AffirmationsController < ApplicationController
  http_basic_authenticate_with name: Rails.application.credentials.admin_name!, password: Rails.application.credentials.admin_secret, except: :random
  def index
    @affirmations = Affirmation.all
  end
  def show
    @affirmation = Affirmation.find(params[:id])
  end

  # Show random affirmation on index page
  def random
    affirmations = Affirmation.all
    @randomAffirmation = affirmations.sample
  end

  # Create and save a new entry
  def new
    @affirmation = Affirmation.new
  end

  def create
    @affirmation = Affirmation.new(affirmation_params)

    if @affirmation.save
      redirect_to @affirmation
    else
      render :new, status: :unprocessable_entity
    end
  end

  # Edit and update a database entry
  def edit
    @affirmation = Affirmation.find(params[:id])
  end

  def update
    @affirmation = Affirmation.find(params[:id])

    if @affirmation.update(affirmation_params)
      redirect_to @affirmation
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # Delete entry
  def destroy
    @affirmation = Affirmation.find(params[:id])
    @affirmation.destroy

    redirect_to "/affirmations", status: :see_other
  end

  # Make sure only allowed params are sent
  private
    def affirmation_params
      params.require(:affirmation).permit(:text)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/helpers/affirmations_helper.rb
module AffirmationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/affirmations/_form.html.erb
<%= form_with model: affirmation do |form| %>
  <div>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
    <% affirmation.errors.full_messages_for(:text).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/affirmations/edit.html.erb
<h1 class="font-bold text-4xl">Affirmation bearbeiten</h1>

<%= render "form", affirmation: @affirmation %>

app/views/affirmations/index.html.erb
<h1 class="font-bold text-4xl mb-4">Übersicht aller Affirmationen</h1>

<ul>
    <% @affirmations.each do |affirmation|%>
        <li class=" px-4 hover:bg-blue-dark rounded">
            <%= link_to affirmation.text, affirmation%>
        </li>
    <% end %>
</ul>

<%= link_to "Neue Affirmation anlegen", new_affirmation_path %>
<%= link_to "Zur Startseite", root_path%>

app/views/affirmations/new.html.erb
<h1 class="font-bold text-4xl">Neue Affirmation</h1>

<%= render "form", affirmation: @affirmation %>

app/views/affirmations/random.html.erb
<h1 class="font-bold text-4xl text-white">Zufällige Affirmation</h1>

<p class="px-4 py-6 mt-6 rounded-xl bg-blue-dark hover:shadow-green-light text-center"><%= @randomAffirmation.text%></p>

app/views/affirmations/show.html.erb
<h1 class="font-bold text-4xl">Detailansicht</h1>

<p class="px-4 py-6 mt-6 rounded-xl bg-blue-dark"><%= @affirmation.text %></p>

<ul>
    <li>
        <%= link_to "Zurück zur Übersicht", "/affirmations" %>
    </li>
    <li>
        <%= link_to "Affirmation überarbeiten", edit_affirmation_path(@affirmation) %>
    </li>
    <li><%= link_to "Affirmation löschen", affirmation_path(@affirmation), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Möchtest Du den Eintrag wirklich löschen?"
                  } %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="bg-blue-medium">
  <head>
    <title><%= content_for(:title) || "Junior Dev Affirmation" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex flex-col items-center">
      <%= yield %>
    </main>
  </body>
</html>